
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - es-network

  backend:            ## container name is elasticsearch-backend 1 but frontend should search by the service name which is correct in our case service name != backend url 
    build: ../backend/app
    expose:
      - "9567"
    depends_on:
      - elasticsearch
    networks:
      - es-network

  frontend:
    build: ../frontend/app
    ports:
      - "9567:9567"
    depends_on:
      - backend
    networks:
      - es-network

networks:
  es-network:
